services:
  # =======================
  #! Keycloak stack
  # =======================
  auth_postgres:
    image: postgres:18
    container_name: auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASS}
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USER} -d ${KEYCLOAK_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    environment:
      # --- Database ---
      KC_DB: ${KEYCLOAK_DB}
      KC_DB_URL: jdbc:postgresql://auth_postgres:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASS}

      # --- HTTP cho chế độ 'start' (prod) ---
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8080"
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: "false"

      # --- Admin ---
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - keycloak-data:/opt/keycloak/data
    command: start
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      auth_postgres:
        condition: service_healthy
    networks:
      - auth_network

  # =======================
  #! HAPI FHIR
  # =======================
  hapi_postgres:
    image: postgres:18
    container_name: hapi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${HAPI_FHIR_DB_NAME}
      POSTGRES_USER: ${HAPI_FHIR_DB_USER}
      POSTGRES_PASSWORD: ${HAPI_FHIR_DB_PASS}
    volumes:
      - hapi-postgres-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${HAPI_FHIR_DB_USER} -d ${HAPI_FHIR_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hapi_network

  hapi_fhir:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir
    restart: unless-stopped
    environment:
      JAVA_OPTS: "-Xms1g -Xmx4g"
      SPRING_DATASOURCE_URL: jdbc:postgresql://hapi_postgres:5432/${HAPI_FHIR_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${HAPI_FHIR_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${HAPI_FHIR_DB_PASS}
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_SEARCH_ENABLED: "false"
      hapi.fhir.fhir_version: R4
      hapi.fhir.ig_runtime_upload_enabled: "true"
    ports:
      - "${FHIR_SERVER_PORT}:8080"
    depends_on:
      hapi_postgres:
        condition: service_healthy
    networks:
      - hapi_network

volumes:
  postgres-data:
  redis-data:
  keycloak-data:
  hapi-postgres-data:


networks:
  auth_network:
    driver: bridge
  hapi_network:
    driver: bridge
